config/routes.rb
ShareMan::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => 'companies#index'
  resources :companies

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :company_shares
  accepts_nested_attributes_for :company_shares, :allow_destroy => true

  has_many :series
  accepts_nested_attributes_for :series, :allow_destroy => true

  validates :name, :presence => true, :uniqueness => true

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/company_share.rb
class CompanyShare < ActiveRecord::Base
  belongs_to :company
  belongs_to :series

  validates :number, :presence => true
  validates :purchased_on, :presence => true
end

app/models/series.rb
class Series < ActiveRecord::Base
  validates :liquidation_order, :presence => true
  validates_uniqueness_of :liquidation_order, :scope => :company_id

  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find params[:id].to_i
    5.times{ @company.series.build }
    5.times{ @company.company_shares.build }
    render 'edit'
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(params[:company])
    if @company.save
      redirect_to @company, :notice => :default
    else
      flash[:alert] = :default
      render 'new'
    end
  end

  def update
    @company = Company.find params[:id].to_i
    cleanup_nested :series_attributes, :name
    cleanup_nested :company_shares_attributes, :shareholder_name

    if @company.update_attributes(params[:company])
      redirect_to @company, :notice => :default
    else
      flash[:alert] = :default
      render 'edit'
    end
  end

  private

  def cleanup_nested(attribute_name, field)
    nested_attributes = params[:company][attribute_name] || {}
    nested_attributes.each do |k,attributes|
      nested_attributes.delete(k) if attributes[field].blank?
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def ping
    render :text => 'pong'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_will_paginate(collection, options={})
    will_paginate(collection, options.merge(:renderer => WillPaginate::ActionView::BootstrapLinkRenderer))
  end

  def nbsp(count=1)
    ("&nbsp;" * count).html_safe
  end

  def form_input_row(f, field, &block)
    text = f.text_field field unless block_given?
    error = 'error' if f.object.errors[field].present?
    input_row(f.label(field), :text => text, :class => error, &block)
  end

  def input_row(label, options={}, &block)
    input = if block_given?
      capture(&block)
    else
      options[:text]
    end

    <<-HTML.html_safe
    <div class="clearfix #{options[:class]}">
      #{label}
      <div class="input">#{ input }</div>
    </div>
    HTML
  end

  def form_button(f)
    f.submit (f.object.new_record? ? 'Create' : 'Save'), :class => 'btn primary'
  end
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= form_input_row f, :name %>

  <% unless @company.new_record? %>
    <h2>Series</h2>
    <table style="width: auto">
      <tr>
        <td>Name</td>
        <td>Liquidation per share</td>
        <td>Liquidation order</td>
        <td>Participation</td>
        <td>Participation cap</td>
        <td></td>
      </tr>

      <%= f.fields_for :series, @company.series do |csf| %>
        <tr>
          <td><%= csf.text_field :name, :style => 'width:100px' %></td>
          <td><%= csf.text_field :liquidation_amount_per_share, :style => 'width:50px' %></td>
          <td><%= csf.text_field :liquidation_order, :style => 'width:20px' %></td>
          <td><%= csf.check_box :participation %></td>
          <td><%= csf.text_field :participation_cap, :style => 'width:50px' %></td>
          <td><%= csf.check_box :_destroy %> Delete</td>
        </tr>
      <% end %>
    </table>

    <h2>Shares</h2>
    <% persisted_series = @company.series.reject(&:new_record?) %>
    <% if persisted_series.present? %>
      <table style="width: auto">
        <tr>
          <td>Shareholder</td>
          <td>Number</td>
          <td>Purchased on</td>
          <td>Series</td>
          <td></td>
        </tr>
        <%= f.fields_for :company_shares, @company.company_shares do |csf| %>
          <tr>
            <td><%= csf.text_field :shareholder_name, :style => 'width: 100px' %></td>
            <td><%= csf.text_field :number, :style => 'width: 40px' %></td>
            <td><%= csf.text_field :purchased_on, :placeholder => 'yyyy-mm-dd', :style => 'width: 80px' %></td>
            <td><%= csf.select :series_id, persisted_series.map{|s| [s.name, s.id] } %></td>
            <td><%= csf.check_box :_destroy %> Delete</td>
          </tr>
        <% end %>
      </table>
    <% else %>
      Add at least 1 series to add shares.
    <% end %>
  <% end %>

  <br/>
  <br/>
  <%= form_button f %>
<% end %>

app/views/companies/edit.html.erb
<h1><%= @company.name %></h1>

<%= render 'form' %>

app/views/companies/index.html.erb
<%= link_to 'New', new_company_path %>

<table>
  <% @companies.each do |company| %>
    <tr>
      <td><%= link_to company.name, company %></td>
    </tr>
  <% end %>
</table>

app/views/companies/new.html.erb
New Company

<%= render 'form' %>

app/views/layouts/_google_analytics.erb
<script>
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= CFG[:api][:google][:analytics] %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ||= 'Share Man' %></title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <h1><%= @page_title %></h1>
  <%= yield %>
</div>

<%= javascript_include_tag "application" %>
<%#= render 'layouts/google_analytics' if Rails.env.production? %>

</body>
</html>